on:
  push:
    branches:
      - master
      - develop
jobs:
  UpdateJsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          cd github-actions
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update jsons
        run: |
          python github-actions/get.py
          git config --global user.name 'leynier'
          git config --global user.email 'leynier41@gmail.com'
          git add .
          git commit --allow-empty -am "Update config jsons"
          git push
